### ISSUE TITLE
Initial release

### ISSUE THREAD

**Issue by viktor-yakubiv** [oacore/dashboard#34]
## Scope overview

The scope is broken down to the variety of task, categorised and ordered by priority (descending).

- [x] Depositing data
  - [x] Create endpoint `/data-provider/<id>/deposit-dates`
  - [x] Display depositing data
    - [x] Develop the table (#39)
    - [x] Design cards for depositing overview and export
    - [x] Integrate the table with the endpoint
- [x] Authorisation
  - [x] Develop endpoints
    - [x] `/login`
      - [x] Support `Content-Type: application/x-www-form-encoded`
      - [ ] Support `Content-Type: application/json`
    - [x] `/logout`
  - [x] Develop `login.html` (#33)
  - [x] Develop logout page (#43)
- [x] Content browsing
  - [x] Create endpoint `/data-providers/<id>/works`
  - [x] Display data-provider's content
    - [x] Table
    - [ ] Overview card
      - [ ] Design
      - [ ] Develop
- [ ] Plug-ins integration 🛑 out of scope candidate
  - [x] Create endpoint `/data-providers/<id>/integrations`
  - [x] Convert installation instructions to Markdown
  - [x] Display instructions
  - [ ] Display real data from the endpoint
    - [ ] Design keys displaying
    - [ ] Integrate key generating 🛑 out of scope candidate

**Comment by viktor-yakubiv** [comment]
I think we did enough to close this.
